### ISSUE TITLE
Data on protein half-lives

### ISSUE THREAD

**Issue by bahler** [dbitton/AnGeLi#7]
A useful data set to add to AnGeLi are the protein half-life data from proliferating cells:
Christiano, R., Nagaraj, N., Fröhlich, F., & Walther, T. C. (2014). Global Proteome Turnover Analyses of the Yeasts S. cerevisiae and S. pombe. Cell Reports, 9, 1959–1965. doi:10.1016/j.celrep.2014.10.065

The half-lives are downloadable in an excel table.

**Comment by dbitton** [comment]
Will be added in the next update, thanks for your suggestion!
