### ISSUE TITLE
add MMS data

### ISSUE THREAD

**Issue by ValWood** [dbitton/AnGeLi#9]
From Nick's request.
Apologies if this is in progress, just clearing out my pending file.

Hi Val,

As it turns out there is MMS data in Jurg's 2003 MBC paper http://www.ncbi.nlm.nih.gov/pubmed/12529438.
It would be great to get this list added to Angeli.

Nick

**Comment by dbitton** [comment]
I quote Jurg "About MMS: Only two genes (abc1; SPAC4F10.10c) are specifically induced in MMS, the rest overlaps with CESR (Chen 2003, MBC). That’s the reason we did not include them as I guess that’s too small a list to be meaningful. Perhaps let Nick know about this."

**Comment by ValWood** [comment]
thanks danny
val

On 28/11/2015 08:56, dbitton wrote:

> I quote Jurg "About MMS: Only two genes (abc1; SPAC4F10.10c) are 
> specifically induced in MMS, the rest overlaps with CESR (Chen 2003, 
> MBC). That’s the reason we did not include them as I guess that’s too 
> small a list to be meaningful. Perhaps let Nick know about this."
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/dbitton/AnGeLi/issues/9#issuecomment-160265188.

## 

Cambridge University
PomBase http://www.pombase.org/
Cambridge Systems Biology Centre http://www.sysbiol.cam.ac.uk/Investigators/val-wood
